from sqlalchemy import MetaData
from sqlalchemy.orm import registry

# Every table in every module registers on this one MetaData, so Alembic sees the
# whole schema. The naming convention gives constraints stable, predictable names,
# which keeps autogenerated migrations reviewable and makes them reversible.
metadata = MetaData(
    naming_convention={
        "ix": "ix_%(column_0_label)s",
        "uq": "uq_%(table_name)s_%(column_0_name)s",
        "ck": "ck_%(table_name)s_%(constraint_name)s",
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
        "pk": "pk_%(table_name)s",
    }
)

# Imperative mapping: domain classes stay plain Python, and each module's
# infrastructure maps them to tables here (ADR 0001).
mapper_registry = registry(metadata=metadata)
