"""catalog

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-25 04:27:34.120396

The first tables of workspace data, so all three end with `isolate_by_workspace`: the API
connects as `wiredex_app`, which row-level security applies to, and migrations run as the
owner, which it doesn't (ADR 0007).

Three details are worth knowing when reading the DDL:

- The sibling-name constraint is `NULLS NOT DISTINCT`, because root categories have no
  parent and Postgres would otherwise take two roots named Passives for different rows.
- MPN uniqueness is a partial unique index over the folded manufacturer and MPN, so
  TI/BME280 collides with ti/bme280, a missing manufacturer counts as the empty string,
  and any number of parts without an MPN is fine.
- The GIN index over `attributes` has no query yet: building it later would mean building
  it over a full table.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from wiredex.shared_kernel.infrastructure.row_security import isolate_by_workspace

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | None = None
depends_on: str | None = None

ISOLATED = ("categories", "attribute_definitions", "part_definitions")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint(
            "workspace_id",
            "parent_id",
            "name",
            name=op.f("uq_categories_workspace_id"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        op.f("ix_categories_workspace_id"), "categories", ["workspace_id"], unique=False
    )
    op.create_table(
        "attribute_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "number",
                "enum",
                "text",
                "bool",
                name="attribute_kind",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("unit", sa.String(length=16), nullable=True),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column(
            "options",
            postgresql.JSONB(),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_attribute_definitions_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attribute_definitions")),
        sa.UniqueConstraint(
            "workspace_id", "category_id", "key", name=op.f("uq_attribute_definitions_workspace_id")
        ),
    )
    op.create_index(
        op.f("ix_attribute_definitions_workspace_id"),
        "attribute_definitions",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "part_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("manufacturer", sa.String(length=80), nullable=True),
        sa.Column("mpn", sa.String(length=80), nullable=True),
        sa.Column("package", sa.String(length=40), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_part_definitions_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_part_definitions")),
    )
    op.create_index(
        op.f("ix_part_definitions_attributes"),
        "part_definitions",
        ["attributes"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_part_definitions_workspace_id"), "part_definitions", ["workspace_id"], unique=False
    )
    op.create_index(
        op.f("ix_part_definitions_workspace_id_category_id"),
        "part_definitions",
        ["workspace_id", "category_id"],
        unique=False,
    )
    op.create_index(
        op.f("uq_part_definitions_mpn"),
        "part_definitions",
        [
            "workspace_id",
            sa.literal_column("lower(coalesce(manufacturer, ''))"),
            sa.literal_column("lower(mpn)"),
        ],
        unique=True,
        postgresql_where=sa.text("mpn IS NOT NULL"),
    )
    # ### end Alembic commands ###
    for table in ISOLATED:
        isolate_by_workspace(op.execute, table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The policies go with their tables: DROP TABLE takes its indexes and policies too.
    op.drop_index(
        op.f("uq_part_definitions_mpn"),
        table_name="part_definitions",
        postgresql_where=sa.text("mpn IS NOT NULL"),
    )
    op.drop_index(
        op.f("ix_part_definitions_workspace_id_category_id"), table_name="part_definitions"
    )
    op.drop_index(op.f("ix_part_definitions_workspace_id"), table_name="part_definitions")
    op.drop_index(
        op.f("ix_part_definitions_attributes"),
        table_name="part_definitions",
        postgresql_using="gin",
    )
    op.drop_table("part_definitions")
    op.drop_index(op.f("ix_attribute_definitions_workspace_id"), table_name="attribute_definitions")
    op.drop_table("attribute_definitions")
    op.drop_index(op.f("ix_categories_workspace_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
