"""pinouts

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-25 09:59:44.189595

A part's pins, one row each, isolated per workspace like the three tables of 0005: the API
connects as `wiredex_app`, which row-level security applies to, and migrations run as the
owner, which it doesn't (ADR 0007). Purely additive, so the release before this one keeps
working against the schema.

Three details are worth knowing when reading the DDL:

- The order is not Alembic's. `pins` points at `part_definitions (workspace_id, id)`, so
  that unique constraint has to exist before the table, and the table has to be gone before
  the constraint can be dropped again. Autogenerate wrote both the other way round.
- The foreign key is on the pair, not on `part_id` alone, because Postgres checks foreign
  keys without row-level security: with the pair, a pin filed under a part of another
  workspace is refused by the database itself (requirement 4.2). `ON DELETE CASCADE` is
  what makes deleting a part delete its pinout.
- `type` is text with a CHECK over the eight pin types, as `attribute_kind` is in 0005, so a
  ninth type is a simple migration and not a new enum type.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from wiredex.shared_kernel.infrastructure.row_security import isolate_by_workspace

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, because the composite foreign key below needs something unique to point at.
    op.create_unique_constraint(
        op.f("uq_part_definitions_workspace_id"), "part_definitions", ["workspace_id", "id"]
    )
    op.create_table(
        "pins",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("part_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=16), nullable=False),
        sa.Column("label", sa.String(length=40), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "power",
                "ground",
                "io",
                "input",
                "output",
                "analog",
                "nc",
                "other",
                name="pin_type",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "functions",
            postgresql.ARRAY(sa.String(length=32)),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column("voltage", sa.Numeric(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id", "part_id"],
            ["part_definitions.workspace_id", "part_definitions.id"],
            name=op.f("fk_pins_workspace_id_part_definitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("part_id", "number", name=op.f("pk_pins")),
        sa.UniqueConstraint("part_id", "position", name=op.f("uq_pins_part_id")),
    )
    op.create_index(
        "ix_pins_functions", "pins", ["functions"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###
    isolate_by_workspace(op.execute, "pins")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The table goes first: its foreign key holds the constraint below in place, and
    # DROP TABLE takes the index and the policy with it.
    op.drop_index("ix_pins_functions", table_name="pins", postgresql_using="gin")
    op.drop_table("pins")
    op.drop_constraint(op.f("uq_part_definitions_workspace_id"), "part_definitions", type_="unique")
    # ### end Alembic commands ###
