"""files

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-25 18:50:13.708220

The files module's two tables of workspace data, so both end with `isolate_by_workspace`:
the API connects as `wiredex_app`, which row-level security applies to, and migrations run
as the owner, which it doesn't (ADR 0007). Purely additive, so the release before this one
keeps working against the schema.

Three details are worth knowing when reading the DDL:

- `files` comes first: `attachments` has a composite foreign key at
  `files (workspace_id, sha256)`, so that table (its primary key is the pair) has to exist
  before it. On the way down the order reverses, which is what Alembic already wrote.
- The foreign key is on the pair, not on `sha256` alone, because Postgres checks foreign
  keys without row-level security: with the pair, a file of another workspace can't be
  attached, the database itself refuses it (ADR 0007). RESTRICT, not CASCADE: a file with
  attachments is never orphaned, and `Detach` drops the file row only once nothing uses it.
- `media_type`, `subject_kind` and `kind` are text with a CHECK over their values, as the
  catalog's `attribute_kind` and `pin_type` are, so one more type or kind is a simple
  migration and not a new enum type. The `size` CHECK bounds a file at 1 byte to 25 MiB, the
  same range `FileSize` validates in the domain (requirement 2.4).
"""

import sqlalchemy as sa
from alembic import op

from wiredex.shared_kernel.infrastructure.row_security import isolate_by_workspace

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | None = None
depends_on: str | None = None

ISOLATED = ("files", "attachments")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "media_type",
            sa.Enum(
                "application/pdf",
                "image/png",
                "image/jpeg",
                "image/webp",
                name="media_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("size BETWEEN 1 AND 26214400", name=op.f("ck_files_size_in_range")),
        sa.PrimaryKeyConstraint("workspace_id", "sha256", name="pk_files"),
    )
    op.create_table(
        "attachments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "subject_kind",
            sa.Enum(
                "part", name="subject_kind", native_enum=False, create_constraint=True, length=16
            ),
            nullable=False,
        ),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "datasheet",
                "image",
                "pinout_diagram",
                "other",
                name="attachment_kind",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "sha256"],
            ["files.workspace_id", "files.sha256"],
            name="fk_attachments_workspace_id_files",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
        sa.UniqueConstraint(
            "workspace_id", "subject_kind", "subject_id", "sha256", name="uq_attachments_subject"
        ),
    )
    op.create_index(
        "ix_attachments_subject",
        "attachments",
        ["workspace_id", "subject_kind", "subject_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_attachments_workspace_id"), "attachments", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###
    for table in ISOLATED:
        isolate_by_workspace(op.execute, table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `attachments` first: its foreign key holds `files` in place, and DROP TABLE takes its
    # indexes and its row-level-security policy with it.
    op.drop_index(op.f("ix_attachments_workspace_id"), table_name="attachments")
    op.drop_index("ix_attachments_subject", table_name="attachments")
    op.drop_table("attachments")
    op.drop_table("files")
    # ### end Alembic commands ###
