"""search

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-25 20:10:00.000000

Trigram indexes for parametric search (requirement 7.1). Case-insensitive substring search
(`ILIKE '%...%'`) over a part's identifying text can't use a plain B-tree; `pg_trgm`'s GIN
indexes serve it. Written by hand rather than autogenerated: Alembic can create the indexes
but not the extension they depend on, and the operator class reads best spelled out.

Index-only and additive, over no new table: nothing here is workspace data, so there is no
`isolate_by_workspace`, and the release before this one keeps working against the schema.

`package` gets no index: it is short and repeated (`0805`), and the category filter narrows
before it. The attributes' GIN index from 0005 and the pins' from 0006 serve the rest.

`downgrade` drops the three indexes but keeps the extension: dropping it could break anything
else that comes to use it, and keeping it costs nothing.
"""

from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | None = None
depends_on: str | None = None

TRIGRAM_INDEXES = {
    "ix_part_definitions_name_trgm": "name",
    "ix_part_definitions_mpn_trgm": "mpn",
    "ix_part_definitions_manufacturer_trgm": "manufacturer",
}


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    for name, column in TRIGRAM_INDEXES.items():
        op.create_index(
            name,
            "part_definitions",
            [column],
            unique=False,
            postgresql_using="gin",
            postgresql_ops={column: "gin_trgm_ops"},
        )


def downgrade() -> None:
    # The extension stays: dropping it could break anything else that uses it.
    for name in TRIGRAM_INDEXES:
        op.drop_index(name, table_name="part_definitions")
