"""inventory

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-26 21:39:41.195496

The second set of workspace-scoped tables (catalog's 0005 were the first), so all five end
with `isolate_by_workspace`: the API connects as `wiredex_app`, which row-level security
applies to, and migrations run as the owner, which it doesn't (ADR 0007).

Details worth knowing when reading the DDL:

- `locations` carries two sibling constraints, so they are named apart by hand: the
  `NULLS NOT DISTINCT` name uniqueness (a root has no parent, and Postgres would otherwise
  take two roots named Lab for different rows) and the per-workspace unique short code.
  Alembic's autogenerator names both `uq_locations_workspace_id`, which collides; the
  explicit names split them.
- The code trigram GIN index needs the `pg_trgm` extension. 0008 already created it and
  keeps it on downgrade, but the `CREATE EXTENSION IF NOT EXISTS` here is idempotent and
  keeps this migration self-contained.
- The `kind` and `reason` columns are text with a CHECK, not Postgres enum types, and
  `kind` lists all seven ADR 0002 names though v0.4.0 writes only three ("expand now,
  contract later").
- `part_id` on `stock_lots` is a bare uuid with no foreign key to `part_definitions`:
  modules don't point at each other's tables. Its existence is checked through the `Parts`
  port.

`downgrade` drops every table in reverse dependency order; DROP TABLE takes its indexes and
row-level-security policies with it, so the round trip (up, down, up) is clean.
"""

import sqlalchemy as sa
from alembic import op

from wiredex.shared_kernel.infrastructure.row_security import isolate_by_workspace

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | None = None
depends_on: str | None = None

ISOLATED = (
    "locations",
    "short_code_counters",
    "stock_lots",
    "stock_movements",
    "stock_balances",
)


def upgrade() -> None:
    # Idempotent: 0008 already created it for the catalog trigram indexes. The location code
    # trigram index below needs it too.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["locations.id"],
            name=op.f("fk_locations_parent_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
        sa.UniqueConstraint("workspace_id", "code", name=op.f("uq_locations_workspace_id_code")),
        sa.UniqueConstraint(
            "workspace_id",
            "parent_id",
            "name",
            name=op.f("uq_locations_workspace_id_parent_id_name"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_locations_code_trgm",
        "locations",
        ["code"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"code": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_locations_workspace_id"), "locations", ["workspace_id"], unique=False)
    op.create_table(
        "short_code_counters",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("next_value", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "kind IN ('location', 'unit')", name=op.f("ck_short_code_counters_kind")
        ),
        sa.PrimaryKeyConstraint("workspace_id", "kind", name=op.f("pk_short_code_counters")),
    )
    op.create_table(
        "stock_lots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("part_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_stock_lots_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_lots")),
        sa.UniqueConstraint(
            "workspace_id", "part_id", "location_id", name=op.f("uq_stock_lots_workspace_id")
        ),
    )
    op.create_index(
        op.f("ix_stock_lots_workspace_id"), "stock_lots", ["workspace_id"], unique=False
    )
    op.create_index(
        "ix_stock_lots_workspace_id_part_id",
        "stock_lots",
        ["workspace_id", "part_id"],
        unique=False,
    )
    op.create_table(
        "stock_balances",
        sa.Column("lot_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("on_hand", sa.Integer(), nullable=False),
        sa.Column("reserved", sa.Integer(), server_default="0", nullable=False),
        sa.Column("available", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "available = on_hand - reserved", name=op.f("ck_stock_balances_available_is_derived")
        ),
        sa.CheckConstraint("on_hand >= 0", name=op.f("ck_stock_balances_on_hand_non_negative")),
        sa.CheckConstraint(
            "reserved >= 0 AND reserved <= on_hand",
            name=op.f("ck_stock_balances_reserved_within_on_hand"),
        ),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["stock_lots.id"],
            name=op.f("fk_stock_balances_lot_id_stock_lots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("lot_id", name=op.f("pk_stock_balances")),
    )
    op.create_index(
        op.f("ix_stock_balances_workspace_id"), "stock_balances", ["workspace_id"], unique=False
    )
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("lot_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "RECEIVE",
                "ADJUST",
                "MOVE",
                "RESERVE",
                "RELEASE",
                "CONSUME",
                "RETURN",
                name="movement_kind",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("change", sa.Integer(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "recount",
                "damaged",
                "lost",
                "found",
                "correction",
                name="movement_reason",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("move_group", sa.Uuid(), nullable=True),
        sa.Column("revision_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["stock_lots.id"],
            name=op.f("fk_stock_movements_lot_id_stock_lots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movements")),
    )
    op.create_index(
        op.f("ix_stock_movements_workspace_id"), "stock_movements", ["workspace_id"], unique=False
    )
    op.create_index(
        "ix_stock_movements_workspace_id_created_at",
        "stock_movements",
        ["workspace_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_stock_movements_workspace_id_lot_id_created_at",
        "stock_movements",
        ["workspace_id", "lot_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
    for table in ISOLATED:
        isolate_by_workspace(op.execute, table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The policies go with their tables: DROP TABLE takes its indexes and policies too.
    op.drop_index("ix_stock_movements_workspace_id_lot_id_created_at", table_name="stock_movements")
    op.drop_index("ix_stock_movements_workspace_id_created_at", table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_workspace_id"), table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index(op.f("ix_stock_balances_workspace_id"), table_name="stock_balances")
    op.drop_table("stock_balances")
    op.drop_index("ix_stock_lots_workspace_id_part_id", table_name="stock_lots")
    op.drop_index(op.f("ix_stock_lots_workspace_id"), table_name="stock_lots")
    op.drop_table("stock_lots")
    op.drop_table("short_code_counters")
    op.drop_index(op.f("ix_locations_workspace_id"), table_name="locations")
    op.drop_index(
        "ix_locations_code_trgm",
        table_name="locations",
        postgresql_using="gin",
        postgresql_ops={"code": "gin_trgm_ops"},
    )
    op.drop_table("locations")
    # ### end Alembic commands ###
