"""units

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-27 13:41:01.043449

The `units` table, the sixth workspace-scoped inventory table, so it ends with
`isolate_by_workspace`: the API connects as `wiredex_app`, which row-level security applies
to, and migrations run as the owner, which it doesn't (ADR 0007). A unit is additional
identity over stock already counted through the ledger, so this migration adds no counting
tables; units point at `stock_lots` and count through the existing balances.

Details worth knowing when reading the DDL:

- `serial` is unique per (workspace, part), lower-cased and only when present:
  `(workspace_id, part_id, lower(serial)) WHERE serial IS NOT NULL`, the mirror of catalog's
  partial MPN index. A serial only means something within a part, so two parts may reuse one
  and any number of units may have none.
- `mac` is unique per workspace, only when present: `(workspace_id, mac) WHERE mac IS NOT
  NULL`. A MAC is globally unique in reality. The stored value is already canonical (the
  `Mac` value object lower-cased it), so the index needs no `lower()`.
- The three trigram GIN indexes (code, mac, serial) power the case-insensitive substring
  search and need the `pg_trgm` extension. 0008 already created it and keeps it on
  downgrade, but the `CREATE EXTENSION IF NOT EXISTS` here is idempotent and keeps this
  migration self-contained.
- `status` is text with a CHECK on the two v0.4.0 values, never a Postgres enum type, so
  v0.5.0's `in_use`/`reserved` is a migration and not an `ALTER TYPE` (the movement CHECK's
  pattern).
- `part_id` is a bare uuid with no foreign key to `part_definitions`: modules don't point at
  each other's tables. Its existence is checked through the `Parts` port. `lot_id` restricts
  deletes so a lot with units can't be dropped out from under them.

`downgrade` drops the table; DROP TABLE takes its indexes and row-level-security policy with
it, so the round trip (up, down, up) is clean.
"""

import sqlalchemy as sa
from alembic import op

from wiredex.shared_kernel.infrastructure.row_security import isolate_by_workspace

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # Idempotent: 0008 already created it for the catalog trigram indexes. The unit code, mac
    # and serial trigram indexes below need it too.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "units",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("part_id", sa.Uuid(), nullable=False),
        sa.Column("lot_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("serial", sa.String(length=80), nullable=True),
        sa.Column("mac", sa.String(length=17), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('in_stock', 'retired')", name=op.f("ck_units_status")),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["stock_lots.id"],
            name=op.f("fk_units_lot_id_stock_lots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units")),
        sa.UniqueConstraint("workspace_id", "code", name="uq_units_workspace_id_code"),
    )
    op.create_index(
        "ix_units_code_trgm",
        "units",
        ["code"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"code": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_units_mac_trgm",
        "units",
        ["mac"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"mac": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_units_serial_trgm",
        "units",
        ["serial"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"serial": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_units_workspace_id"), "units", ["workspace_id"], unique=False)
    op.create_index(
        "ix_units_workspace_id_lot_id", "units", ["workspace_id", "lot_id"], unique=False
    )
    op.create_index(
        "ix_units_workspace_id_part_id", "units", ["workspace_id", "part_id"], unique=False
    )
    op.create_index(
        "uq_units_workspace_id_mac",
        "units",
        ["workspace_id", "mac"],
        unique=True,
        postgresql_where=sa.text("mac IS NOT NULL"),
    )
    op.create_index(
        "uq_units_workspace_id_part_id_serial",
        "units",
        ["workspace_id", "part_id", sa.literal_column("lower(serial)")],
        unique=True,
        postgresql_where=sa.text("serial IS NOT NULL"),
    )
    # ### end Alembic commands ###
    isolate_by_workspace(op.execute, "units")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_units_workspace_id_part_id_serial",
        table_name="units",
        postgresql_where=sa.text("serial IS NOT NULL"),
    )
    op.drop_index(
        "uq_units_workspace_id_mac", table_name="units", postgresql_where=sa.text("mac IS NOT NULL")
    )
    op.drop_index("ix_units_workspace_id_part_id", table_name="units")
    op.drop_index("ix_units_workspace_id_lot_id", table_name="units")
    op.drop_index(op.f("ix_units_workspace_id"), table_name="units")
    op.drop_index(
        "ix_units_serial_trgm",
        table_name="units",
        postgresql_using="gin",
        postgresql_ops={"serial": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_units_mac_trgm",
        table_name="units",
        postgresql_using="gin",
        postgresql_ops={"mac": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_units_code_trgm",
        table_name="units",
        postgresql_using="gin",
        postgresql_ops={"code": "gin_trgm_ops"},
    )
    op.drop_table("units")
    # ### end Alembic commands ###
