"""projects

Revision ID: 0013
Revises: 0012
Create Date: 2026-09-28 12:02:09.306500

The `projects` and `revisions` tables, the third set of workspace-scoped tables after
catalog's and inventory's, so both end with `isolate_by_workspace`: the API connects as
`wiredex_app`, which row-level security applies to, and migrations run as the owner, which it
doesn't (ADR 0007). Purely additive, so the release before this one keeps working against the
schema.

Details worth knowing when reading the DDL:

- A revision points at its project by the pair `(workspace_id, project_id)`, not by
  `project_id` alone, because Postgres checks foreign keys without row-level security: with
  the pair, a revision filed under another workspace's project is refused by the database
  itself (requirement 8.4). `uq_projects_workspace_id` is what that key points at, and
  `ON DELETE CASCADE` is what makes deleting a project delete its revisions.
- `forked_from` points at the revision a fork was made from, `ON DELETE SET NULL`, so deleting
  the source keeps the fork. Its index keeps that `SET NULL` from scanning the table.
- Names and labels are unique folded, by two expression indexes: `(workspace_id, lower(name))`
  and `(workspace_id, project_id, lower(label))`.
- `tags` is a `varchar(32)[]` like `pins.functions`, with a GIN index for `tags @> ARRAY[…]`
  and a CHECK repeating the domain's cap of twenty.
- `status` is text with a CHECK over ADR 0003's four states, never a Postgres enum type,
  though only `draft` is written yet: 10-build-lifecycle adds transitions, not a migration.

`downgrade` drops `revisions`, then `projects`, whose unique pair the revisions' key holds in
place; DROP TABLE takes the indexes and the row-level-security policies with it, so the round
trip (up, down, up) is clean.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from wiredex.shared_kernel.infrastructure.row_security import isolate_by_workspace

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | None = None
depends_on: str | None = None

ISOLATED = ("projects", "revisions")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=4000), nullable=True),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.String(length=32)),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("cardinality(tags) <= 20", name=op.f("ck_projects_at_most_twenty_tags")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_projects_workspace_id")),
    )
    op.create_index("ix_projects_tags", "projects", ["tags"], unique=False, postgresql_using="gin")
    op.create_index(op.f("ix_projects_workspace_id"), "projects", ["workspace_id"], unique=False)
    op.create_index(
        "uq_projects_name",
        "projects",
        ["workspace_id", sa.literal_column("lower(name)")],
        unique=True,
    )
    op.create_table(
        "revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.String(length=4000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "reserved",
                "built",
                "dismantled",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("forked_from", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["forked_from"],
            ["revisions.id"],
            name=op.f("fk_revisions_forked_from_revisions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "project_id"],
            ["projects.workspace_id", "projects.id"],
            name=op.f("fk_revisions_workspace_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revisions")),
    )
    op.create_index(op.f("ix_revisions_forked_from"), "revisions", ["forked_from"], unique=False)
    op.create_index(op.f("ix_revisions_workspace_id"), "revisions", ["workspace_id"], unique=False)
    op.create_index(
        "uq_revisions_label",
        "revisions",
        ["workspace_id", "project_id", sa.literal_column("lower(label)")],
        unique=True,
    )
    # ### end Alembic commands ###
    for table in ISOLATED:
        isolate_by_workspace(op.execute, table)


def downgrade() -> None:
    # Revisions first: their foreign key holds the projects' unique pair in place. DROP TABLE
    # takes each table's indexes, constraints and policy with it.
    op.drop_table("revisions")
    op.drop_table("projects")
