"""bill of materials

Revision ID: 0017
Revises: 0016
Create Date: 2026-09-28 17:41:37.391239

A revision's bill of materials: `bom_lines`, one row per line, and `bom_designators`, one row
per designator a line fills (09's decision 8). Both are workspace-scoped, so both end with
`isolate_by_workspace`: the API connects as `wiredex_app`, which row-level security applies
to, and migrations run as the owner, which it doesn't (ADR 0007).

Details worth knowing when reading the DDL:

- `uq_revisions_workspace_id`, a unique `(workspace_id, id)` on `revisions`, always true since
  `id` is the key, comes first: a foreign key can only point at a unique constraint, and the
  lines' key points at this pair. With it, Postgres, which checks foreign keys without
  row-level security, refuses a line of one workspace filed under another's revision.
- A designator points at its line by `(workspace_id, revision_id, line_id)`, which
  `uq_bom_lines_workspace_id` holds unique, so a designator can only belong to a line of its
  own revision and the primary key `(workspace_id, revision_id, designator)` that makes it
  unique per revision can't disagree with its line. 11's pin references will point here.
- Deleting cascades, and nothing else does: a revision takes its lines, a line its
  designators.
- `part_id` has no foreign key: it names catalog's part definition, and modules don't point
  at each other's tables. `ix_bom_lines_part` answers catalog's question, at every part
  deletion, of whether a BOM names the part.
- The designator CHECK is the canonical form, upper-case letters and no leading zero; the
  quantity CHECK repeats the domain's 1 to 10,000.

Purely additive: a unique constraint and two new tables, so the release before this one keeps
working against the schema. `downgrade` drops `bom_designators`, then `bom_lines`, whose key
holds the revisions' pair in place, then that pair; DROP TABLE takes the indexes and the
row-level-security policies with it, so the round trip (up, down, up) is clean. It drops every
BOM with its tables, which is what undoing a table-creating migration means.
"""

import sqlalchemy as sa
from alembic import op

from wiredex.shared_kernel.infrastructure.row_security import isolate_by_workspace

revision: str = "0017"
down_revision: str | None = "0016"
branch_labels: str | None = None
depends_on: str | None = None

ISOLATED = ("bom_lines", "bom_designators")


def upgrade() -> None:
    # First: the lines' composite key below points at it.
    op.create_unique_constraint(
        op.f("uq_revisions_workspace_id"), "revisions", ["workspace_id", "id"]
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bom_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("part_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "quantity BETWEEN 1 AND 10000", name=op.f("ck_bom_lines_quantity_in_range")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "revision_id"],
            ["revisions.workspace_id", "revisions.id"],
            name=op.f("fk_bom_lines_workspace_id_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bom_lines")),
        sa.UniqueConstraint(
            "workspace_id", "revision_id", "id", name=op.f("uq_bom_lines_workspace_id")
        ),
    )
    op.create_index("ix_bom_lines_part", "bom_lines", ["workspace_id", "part_id"], unique=False)
    op.create_index(op.f("ix_bom_lines_workspace_id"), "bom_lines", ["workspace_id"], unique=False)
    op.create_table(
        "bom_designators",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("line_id", sa.Uuid(), nullable=False),
        sa.Column("designator", sa.String(length=12), nullable=False),
        sa.CheckConstraint(
            "designator ~ '^[A-Z]{1,8}[1-9][0-9]{0,3}$'", name=op.f("ck_bom_designators_canonical")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "revision_id", "line_id"],
            ["bom_lines.workspace_id", "bom_lines.revision_id", "bom_lines.id"],
            name=op.f("fk_bom_designators_workspace_id_bom_lines"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "workspace_id", "revision_id", "designator", name=op.f("pk_bom_designators")
        ),
    )
    op.create_index(
        "ix_bom_designators_line",
        "bom_designators",
        ["workspace_id", "revision_id", "line_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    for table in ISOLATED:
        isolate_by_workspace(op.execute, table)


def downgrade() -> None:
    # Designators first, whose key holds the lines' triple in place, then the lines, whose key
    # holds the revisions' pair. DROP TABLE takes each table's indexes and policy with it.
    op.drop_table("bom_designators")
    op.drop_table("bom_lines")
    op.drop_constraint(op.f("uq_revisions_workspace_id"), "revisions", type_="unique")
