"""firmware

Revision ID: 0020
Revises: 0019
Create Date: 2026-09-30 18:17:32.161231

The firmware module's four tables (13-firmware-versions, Data Models): `firmware`, one row per
firmware; `firmware_revisions`, one row per revision a firmware runs on; `firmware_versions`,
one row per version; and `source_files`, one row per file of a version. All four are
workspace-scoped, so all four end with `isolate_by_workspace`: the API connects as
`wiredex_app`, which row-level security applies to, and migrations run as the owner, which it
doesn't (ADR 0007).

Details worth knowing when reading the DDL:

- A link and a version point at their firmware by `(workspace_id, firmware_id)`, against
  `uq_firmware_workspace_id`, and a file at its version by `(workspace_id, version_id)`,
  against `uq_firmware_versions_workspace_id`: Postgres checks foreign keys without row-level
  security, so the pairs are what refuse a row filed under another workspace's firmware or
  version (requirement 9.4).
- Deleting cascades: a firmware takes its links and its versions, a version its files. A
  version's `based_on`, the version it was started from, is `SET NULL` instead, so deleting a
  base keeps the versions started from it (requirement 8.2); its index keeps that `SET NULL`
  from scanning the table.
- `revision_id` has no foreign key: it names projects' revision, and modules don't point at
  each other's tables (decision 2). A link outlives its revision, and reads leave it out
  (decision 3).
- Names are unique per workspace folded, `uq_firmware_name` on `lower(name)`, and paths per
  version, `uq_source_files_path` on `lower(path)`. A number is unique per firmware as stored,
  `uq_firmware_versions_version`, since it is written lower-cased (decision 6).
- `framework` and `status` are text with a CHECK, never a Postgres enum type (decision 11).
  `released_dated` dates a release and only a release; `size_is_length` holds each file's
  `size` to its text's bytes, which a version's limit sums without reading the text
  (decision 9).

Purely additive: four new tables, and nothing that exists changes, so the release before this
one keeps working against the schema. `downgrade` drops the files, the versions, the links and
then the firmware; DROP TABLE takes the indexes and the policies with it, so the round trip
(up, down, up) is clean. It drops every firmware with its tables, which is what undoing a
table-creating migration means.
"""

import sqlalchemy as sa
from alembic import op

from wiredex.shared_kernel.infrastructure.row_security import isolate_by_workspace

revision: str = "0020"
down_revision: str | None = "0019"
branch_labels: str | None = None
depends_on: str | None = None

ISOLATED = ("firmware", "firmware_revisions", "firmware_versions", "source_files")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "firmware",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("target", sa.String(length=200), nullable=False),
        sa.Column(
            "framework",
            sa.Enum(
                "arduino",
                "platformio",
                "esp_idf",
                "micropython",
                "other",
                name="framework",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=4000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_firmware")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_firmware_workspace_id")),
    )
    op.create_index(op.f("ix_firmware_workspace_id"), "firmware", ["workspace_id"], unique=False)
    op.create_index(
        "uq_firmware_name",
        "firmware",
        ["workspace_id", sa.literal_column("lower(name)")],
        unique=True,
    )
    op.create_table(
        "firmware_revisions",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("firmware_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "firmware_id"],
            ["firmware.workspace_id", "firmware.id"],
            name=op.f("fk_firmware_revisions_workspace_id_firmware"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "workspace_id", "firmware_id", "revision_id", name=op.f("pk_firmware_revisions")
        ),
    )
    op.create_index(
        "ix_firmware_revisions_revision",
        "firmware_revisions",
        ["workspace_id", "revision_id"],
        unique=False,
    )
    op.create_table(
        "firmware_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("firmware_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("changelog", sa.String(length=4000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "released",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("based_on", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'released') = (released_at IS NOT NULL)",
            name=op.f("ck_firmware_versions_released_dated"),
        ),
        sa.ForeignKeyConstraint(
            ["based_on"],
            ["firmware_versions.id"],
            name=op.f("fk_firmware_versions_based_on_firmware_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "firmware_id"],
            ["firmware.workspace_id", "firmware.id"],
            name=op.f("fk_firmware_versions_workspace_id_firmware"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_firmware_versions")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_firmware_versions_workspace_id")),
    )
    op.create_index(
        op.f("ix_firmware_versions_based_on"), "firmware_versions", ["based_on"], unique=False
    )
    op.create_index(
        "uq_firmware_versions_version",
        "firmware_versions",
        ["workspace_id", "firmware_id", "version"],
        unique=True,
    )
    op.create_table(
        "source_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "size = octet_length(content)", name=op.f("ck_source_files_size_is_length")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "version_id"],
            ["firmware_versions.workspace_id", "firmware_versions.id"],
            name=op.f("fk_source_files_workspace_id_firmware_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_files")),
    )
    op.create_index(
        "uq_source_files_path",
        "source_files",
        ["workspace_id", "version_id", sa.literal_column("lower(path)")],
        unique=True,
    )
    # ### end Alembic commands ###
    for table in ISOLATED:
        isolate_by_workspace(op.execute, table)


def downgrade() -> None:
    # Files first, whose key holds the versions' pair in place, then the versions and the links,
    # whose keys hold the firmware's. DROP TABLE takes each table's indexes and policy with it.
    op.drop_table("source_files")
    op.drop_table("firmware_versions")
    op.drop_table("firmware_revisions")
    op.drop_table("firmware")
