"""flashes

Revision ID: 0021
Revises: 0020
Create Date: 2026-10-01 11:03:41.668856

The flash log's table (15-flash-log, Data Models): `flashes`, one row per released version
written onto a unit, ADR 0006's deployment. It is workspace-scoped, so it ends with
`isolate_by_workspace`: the API connects as `wiredex_app`, which row-level security applies to,
and migrations run as the owner, which it doesn't (ADR 0007).

Details worth knowing when reading the DDL:

- A flash points at its version by `(workspace_id, version_id)`, against
  `uq_firmware_versions_workspace_id`, as a source file does: Postgres checks foreign keys
  without row-level security, so the pair is what refuses a flash filed under another
  workspace's version (requirement 6.3).
- The key is `ON DELETE RESTRICT`, where every other key of firmware's cascades: deleting a
  version a flash names fails, and so does deleting its firmware, whose cascade to the version
  reaches the key (decision 6, requirements 5.1 and 5.2).
- `unit_id` and `revision_id` have no foreign key: they name inventory's unit and projects'
  revision, and modules don't point at each other's tables (decision 1). A flash outlives both:
  `unit_code` keeps the unit's code as it was minted, and `revision_id` the revision holding the
  unit when the flash was logged (decision 3).
- `ix_flashes_unit` leads with the workspace and the unit, then the log's own order, newest
  first (decision 4): a unit's log and each unit's newest flash, which a firmware's boards read
  with `DISTINCT ON (unit_id)` (decision 11), come in index order. `ix_flashes_version` serves
  the refusals' reads and the key's check when a version is deleted.

Purely additive: one new table, and nothing that exists changes, so the release before this one
keeps working against the schema. `downgrade` drops the table; DROP TABLE takes its indexes and
its policy with it, so the round trip (up, down, up) is clean. It drops every flash, which is
what undoing a table-creating migration means.
"""

import sqlalchemy as sa
from alembic import op

from wiredex.shared_kernel.infrastructure.row_security import isolate_by_workspace

revision: str = "0021"
down_revision: str | None = "0020"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flashes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("unit_code", sa.String(length=16), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=True),
        sa.Column("flashed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "version_id"],
            ["firmware_versions.workspace_id", "firmware_versions.id"],
            name=op.f("fk_flashes_workspace_id_firmware_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flashes")),
    )
    op.create_index(
        "ix_flashes_unit",
        "flashes",
        [
            "workspace_id",
            "unit_id",
            sa.literal_column("flashed_at DESC"),
            sa.literal_column("created_at DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
    )
    op.create_index("ix_flashes_version", "flashes", ["workspace_id", "version_id"], unique=False)
    # ### end Alembic commands ###
    isolate_by_workspace(op.execute, "flashes")


def downgrade() -> None:
    # Nothing keys into the flashes, so the table goes alone. DROP TABLE takes its indexes and
    # its policy with it.
    op.drop_table("flashes")
