"""The `wiredex` command line. Every background job is a command here (ADR 0011)."""

import asyncio
import logging
import sys

import click
from alembic import command
from alembic.config import Config

from wiredex.bootstrap.identity import create_account_use_case
from wiredex.bootstrap.migrations import alembic_config, next_revision_id
from wiredex.bootstrap.settings import Settings
from wiredex.identity.application.create_account import CreatedAccount, NewAccount
from wiredex.identity.domain.errors import IdentityError
from wiredex.identity.domain.values import Email, Name, Password


@click.group()
def cli() -> None:
    """Wiredex administration."""
    # Show Alembic's progress ("Running upgrade 0001 -> 0002, ..."): there is no
    # alembic.ini to configure its logging.
    logging.basicConfig(format="%(message)s")
    logging.getLogger("alembic").setLevel(logging.INFO)


@cli.group()
def db() -> None:
    """Database schema migrations."""


@db.command()
@click.argument("revision", default="head")
def upgrade(revision: str) -> None:
    """Apply migrations up to REVISION (default: the newest)."""
    command.upgrade(_config(), revision)


@db.command()
@click.argument("revision")
def downgrade(revision: str) -> None:
    """Revert migrations down to REVISION (e.g. 0001, or base for an empty schema)."""
    command.downgrade(_config(), revision)


@db.command()
@click.option("-m", "--message", required=True, help="What the migration does.")
@click.option("--empty", is_flag=True, help="Write an empty migration instead of autogenerating.")
def revision(message: str, empty: bool) -> None:
    """Create the next migration, autogenerated from the models by default."""
    config = _config()
    command.revision(
        config, message=message, autogenerate=not empty, rev_id=next_revision_id(config)
    )


@db.command()
def check() -> None:
    """Fail if the models have changes that no migration covers."""
    command.check(_config())


@db.command()
def current() -> None:
    """Show the revision the database is at."""
    command.current(_config())


@cli.group()
def users() -> None:
    """User accounts. There is no public sign-up: accounts are made here (ADR 0008)."""


@users.command("create")
@click.option("--email", required=True, help="Login email; stored lower-cased.")
@click.option("--name", required=True, help="Display name, also the workspace's name.")
@click.option(
    "--password-stdin",
    is_flag=True,
    help="Read the password from standard input instead of prompting (for scripts).",
)
def create_user(email: str, name: str, password_stdin: bool) -> None:
    """Create an account with its own personal workspace, as its owner."""
    try:
        account = NewAccount(Email(email), Name(name), Password(_read_password(password_stdin)))
        created = asyncio.run(_create_account(account))
    except IdentityError as error:
        raise click.ClickException(str(error)) from error
    click.echo(f"Created {account.email}, owner of workspace {created.workspace_id}.")


def _read_password(from_stdin: bool) -> str:
    # Never a command-line argument: those end up in shell history and `ps`.
    if from_stdin:
        return sys.stdin.readline().rstrip("\n")
    password: str = click.prompt("Password", hide_input=True, confirmation_prompt=True)
    return password


async def _create_account(account: NewAccount) -> CreatedAccount:
    async with create_account_use_case(Settings()) as create_account:
        return await create_account(account)


def _config() -> Config:
    return alembic_config(Settings().database_url.get_secret_value())
