"""The `wiredex` command line. Every background job is a command here (ADR 0011)."""

import asyncio
import logging
import secrets
import sys
import tempfile
from datetime import UTC, datetime
from pathlib import Path

import click
from alembic import command
from alembic.config import Config

from wiredex.bootstrap import firmware_build
from wiredex.bootstrap.demo import invite_with_bench, restore_benches
from wiredex.bootstrap.files import (
    clear_workspace_use_case,
    prune_orphans_use_case,
)
from wiredex.bootstrap.identity import (
    create_account_use_case,
    list_all_workspaces_use_case,
    list_demo_workspaces_use_case,
    list_workspaces_of_use_case,
    remove_expired_guests_use_case,
)
from wiredex.bootstrap.inventory import rebuild_balances_use_case
from wiredex.bootstrap.migrations import (
    APP_ROLE,
    AppLogin,
    AppLoginError,
    alembic_config,
    let_app_role_log_in,
    next_revision_id,
)
from wiredex.bootstrap.settings import Settings
from wiredex.bootstrap.wipe import wipe_workspace
from wiredex.files.domain.values import WorkspaceId as FilesWorkspaceId
from wiredex.identity.application.create_account import (
    CreatedAccount,
    GuestInvitation,
    NewAccount,
)
from wiredex.identity.domain.errors import IdentityError
from wiredex.identity.domain.values import Email, GuestLifetime, Name, Password
from wiredex.inventory.domain.values import WorkspaceId as InventoryWorkspaceId


@click.group()
def cli() -> None:
    """Wiredex administration."""
    # Show Alembic's progress ("Running upgrade 0001 -> 0002, ..."): there is no
    # alembic.ini to configure its logging.
    logging.basicConfig(format="%(message)s")
    logging.getLogger("alembic").setLevel(logging.INFO)


@cli.group()
def db() -> None:
    """Database schema migrations."""


@db.command()
@click.argument("revision", default="head")
def upgrade(revision: str) -> None:
    """Apply migrations up to REVISION (default: the newest), then let the API log in."""
    settings = Settings()
    # Checked first: a bad URL must stop a deploy before the schema changes.
    try:
        login = AppLogin.from_url(settings.database_url.get_secret_value())
    except AppLoginError as error:
        raise click.ClickException(str(error)) from error
    command.upgrade(_config(settings), revision)
    admin_url = settings.admin_database_url.get_secret_value()
    if asyncio.run(let_app_role_log_in(admin_url, login)):
        click.echo(f"{APP_ROLE} can log in with the password in WIREDEX_DATABASE_URL.")


@db.command()
@click.argument("revision")
def downgrade(revision: str) -> None:
    """Revert migrations down to REVISION (e.g. 0001, or base for an empty schema)."""
    command.downgrade(_config(), revision)


@db.command()
@click.option("-m", "--message", required=True, help="What the migration does.")
@click.option("--empty", is_flag=True, help="Write an empty migration instead of autogenerating.")
def revision(message: str, empty: bool) -> None:
    """Create the next migration, autogenerated from the models by default."""
    config = _config()
    command.revision(
        config, message=message, autogenerate=not empty, rev_id=next_revision_id(config)
    )


@db.command()
def check() -> None:
    """Fail if the models have changes that no migration covers."""
    command.check(_config())


@db.command()
def current() -> None:
    """Show the revision the database is at."""
    command.current(_config())


@cli.group()
def users() -> None:
    """User accounts. There is no public sign-up: accounts are made here (ADR 0008)."""


@users.command("create")
@click.option("--email", required=True, help="Login email; stored lower-cased.")
@click.option("--name", required=True, help="Display name, also the workspace's name.")
@click.option(
    "--password-stdin",
    is_flag=True,
    help="Read the password from standard input instead of prompting (for scripts).",
)
def create_user(email: str, name: str, password_stdin: bool) -> None:
    """Create an account with its own personal workspace, as its owner."""
    try:
        account = NewAccount(Email(email), Name(name), Password(_read_password(password_stdin)))
        created = asyncio.run(_create_account(account))
    except IdentityError as error:
        raise click.ClickException(str(error)) from error
    click.echo(f"Created {account.email}, owner of workspace {created.workspace_id}.")


def _read_password(from_stdin: bool, *, confirm: bool = True) -> str:
    # Never a command-line argument: those end up in shell history and `ps`. Typed twice when
    # it is being set, once when it is only being checked.
    if from_stdin:
        return sys.stdin.readline().rstrip("\n")
    password: str = click.prompt("Password", hide_input=True, confirmation_prompt=confirm)
    return password


async def _create_account(account: NewAccount) -> CreatedAccount:
    async with create_account_use_case(Settings()) as create_account:
        return await create_account(account)


@cli.group()
def demo() -> None:
    """Guest accounts, each in a demo workspace of its own (ADR 0007)."""


@demo.command("invite")
@click.option("--email", required=True, help="The guest's login email.")
@click.option("--name", default="Guest", show_default=True, help="How the app greets them.")
@click.option(
    "--expires",
    "lifetime",
    default="7d",
    show_default=True,
    help="How long the account works: 12h, 7d, 2w... up to 90d.",
)
def invite(email: str, name: str, lifetime: str) -> None:
    """Invite a guest. Prints a new password once: send it to them with the email."""
    password = secrets.token_urlsafe(12)  # 16 characters, 96 random bits
    try:
        account = NewAccount(Email(email), Name(name), Password(password))
        invitation = GuestInvitation(account, GuestLifetime.parse(lifetime))
        invited = asyncio.run(_invite(invitation))
    except IdentityError as error:
        raise click.ClickException(str(error)) from error
    click.echo(f"Invited {account.email} until {invited.expires_at:%Y-%m-%d %H:%M %Z}.")
    click.echo(f"Password, shown only now: {password}")


async def _invite(invitation: GuestInvitation) -> CreatedAccount:
    return await invite_with_bench(Settings(), invitation)


@demo.command("reset")
def reset() -> None:
    """Nightly demo upkeep, run by a systemd timer: remove the guests whose access ended,
    then wipe each remaining bench's uploads and put its sample data back (ADR 0007)."""
    removed, restored = asyncio.run(_reset())
    click.echo(f"Removed {removed} expired guest account(s).")
    click.echo(f"Restored the sample catalog of {restored} demo workspace(s).")


async def _reset() -> tuple[int, int]:
    """The halves of a reset, in order: the expired guests go, then each bench left is
    cleared of its uploads and seeded again. Only this file knows every module, which is
    what keeps them apart. Files come before the sample data so a bench is emptied of a
    guest's datasheets, photos and Gerbers (requirement 5.3) before its samples return."""
    settings = Settings()
    async with remove_expired_guests_use_case(settings) as remove_expired_guests:
        removed = await remove_expired_guests()
    async with (
        list_demo_workspaces_use_case(settings) as list_demo_workspaces,
        clear_workspace_use_case(settings) as clear_workspace,
    ):
        benches = await list_demo_workspaces()
        for bench in benches:
            await clear_workspace(FilesWorkspaceId(bench))
    await restore_benches(settings, benches)
    return removed, len(benches)


@cli.group()
def workspace() -> None:
    """A workspace's data as a whole."""


@workspace.command("clear")
@click.option("--email", required=True, help="The account whose workspace is emptied.")
@click.option("--yes", is_flag=True, help="Don't ask: for scripts.")
def clear_workspace_data(email: str, yes: bool) -> None:
    """Delete everything in an account's workspace: parts, stock, projects, firmware, files
    and history. The account and its login stay. There is no undo but a backup."""
    try:
        address = Email(email)
    except IdentityError as error:
        raise click.ClickException(str(error)) from error
    if not yes:
        click.confirm(f"Delete everything in the workspace of {address}?", abort=True)
    try:
        cleared = asyncio.run(_clear_workspaces_of(address))
    except IdentityError as error:
        raise click.ClickException(str(error)) from error
    click.echo(f"Emptied {cleared} workspace(s) of {address}.")


async def _clear_workspaces_of(email: Email) -> int:
    settings = Settings()
    async with list_workspaces_of_use_case(settings) as list_workspaces_of:
        workspaces = await list_workspaces_of(email)
    for workspace_id in workspaces:
        await wipe_workspace(settings, workspace_id)
    return len(workspaces)


@cli.group()
def files() -> None:
    """Stored files: the nightly prune of orphaned attachments and objects (ADR 0011)."""


@files.command("prune")
def prune() -> None:
    """Nightly sweep, run by a systemd timer: across every workspace, drop attachments whose
    part is gone, file rows no attachment uses, and objects no row names (requirement 4.4)."""
    workspaces = asyncio.run(_prune())
    click.echo(f"Pruned orphaned files in {workspaces} workspace(s).")


async def _prune() -> int:
    """PruneOrphans once per workspace: identity lists them, the files module sweeps each.
    Only this file knows both modules, which is what keeps them apart."""
    settings = Settings()
    async with (
        list_all_workspaces_use_case(settings) as list_all_workspaces,
        prune_orphans_use_case(settings) as prune_orphans,
    ):
        workspaces = await list_all_workspaces()
        for workspace_id in workspaces:
            await prune_orphans(FilesWorkspaceId(workspace_id))
    return len(workspaces)


@cli.group()
def firmware() -> None:
    """Firmware builds, made on this computer and kept with their version."""


@firmware.command("build")
@click.argument("name")
@click.argument("version")
@click.option("--url", envvar="WIREDEX_URL", required=True, help="Where Wiredex is served.")
@click.option("--email", envvar="WIREDEX_EMAIL", required=True, help="The account to log in as.")
@click.option(
    "--password-stdin",
    is_flag=True,
    help="Read the password from standard input instead of prompting (for scripts).",
)
@click.option(
    "--arduino-cli",
    "arduino",
    default="arduino-cli",
    show_default=True,
    help="The arduino-cli to compile with, by name or path.",
)
def build_firmware(  # noqa: PLR0913 - click passes one argument per option
    name: str, version: str, *, url: str, email: str, password_stdin: bool, arduino: str
) -> None:
    """Compile a released VERSION of the firmware NAME and store the binaries with it.

    Runs on a computer with arduino-cli and the board's core installed, not on the server. It
    logs in, reads the version's source, compiles it for the firmware's board, attaches the
    binaries to the version as a build, and logs out. Flash from the browser then needs no
    file chosen.
    """
    try:
        # Before the password is asked for: a missing compiler or a bad address stops here.
        compiler = firmware_build.arduino_cli(arduino)
        api = firmware_build.Api(firmware_build.urllib_transport(url))
        api.log_in(email, _read_password(password_stdin, confirm=False))
        try:
            with tempfile.TemporaryDirectory(prefix="wiredex-build-") as workdir:
                built = firmware_build.build_version(
                    api,
                    compiler,
                    name=name,
                    number=version,
                    workdir=Path(workdir),
                    now=lambda: datetime.now(UTC),
                )
        finally:
            api.log_out()
    except firmware_build.BuildError as error:
        raise click.ClickException(str(error)) from error
    click.echo(f"Stored “{built.title}” ({built.size:,} bytes) on {name} {version}:")
    for image in built.images:
        click.echo(f"  0x{image.offset:x}  {image.file}  ({len(image.data):,} bytes)")


@cli.group()
def stock() -> None:
    """Stock upkeep: recomputing the balance projection from the ledger (ADR 0002)."""


@stock.command("rebuild")
def rebuild() -> None:
    """Recompute every balance from the ledger, one transaction per workspace (5.2, 5.3).

    A manual repair tool, not a nightly job: run it when a projection is distrusted, and it
    rewrites each bench's balances from the movements that are the source of truth."""
    workspaces = asyncio.run(_rebuild())
    click.echo(f"Rebuilt stock balances in {workspaces} workspace(s).")


async def _rebuild() -> int:
    """RebuildBalances once per workspace: identity lists them, inventory rebuilds each.
    Only this file knows both modules, which is what keeps them apart. Every workspace is
    swept, personal and demo alike, so it is `list_all_workspaces` as the prune uses."""
    settings = Settings()
    async with (
        list_all_workspaces_use_case(settings) as list_all_workspaces,
        rebuild_balances_use_case(settings) as rebuild_balances,
    ):
        workspaces = await list_all_workspaces()
        for workspace_id in workspaces:
            await rebuild_balances(InventoryWorkspaceId(workspace_id))
    return len(workspaces)


def _config(settings: Settings | None = None) -> Config:
    settings = settings or Settings()
    return alembic_config(settings.admin_database_url.get_secret_value())
