import createClient from "openapi-fetch";
import type { components, paths } from "./generated/schema";

export type { Middleware } from "openapi-fetch";
export type { components, paths };
export type Schemas = components["schemas"];
export type VersionInfo = Schemas["VersionResponse"];
export type UserInfo = Schemas["UserResponse"];
export type SessionInfo = Schemas["SessionResponse"];
export type CategoryNode = Schemas["CategoryNodeResponse"];
export type PartSummary = Schemas["PartSummaryResponse"];
export type PartPage = Schemas["PartPageResponse"];
export type PartDetails = Schemas["PartResponse"];
export type CategorySchema = Schemas["CategorySchemaResponse"];
export type SchemaAttribute = Schemas["SchemaAttributeResponse"];
export type AttributeKind = Schemas["AttributeKindName"];
export type AttributeValue = Schemas["AttributeValueResponse"];
export type RawAttributeValue = Schemas["RawAttributeValue"];
export type PartSearchRequest = Schemas["PartSearchRequest"];
export type PartSearchResponse = Schemas["PartSearchResponse"];
export type SearchResult = Schemas["SearchResultResponse"];
export type FilterRequest = Schemas["FilterRequest"];
export type RangeFilterRequest = Schemas["RangeFilterRequest"];
export type OptionsFilterRequest = Schemas["OptionsFilterRequest"];
export type BoolFilterRequest = Schemas["BoolFilterRequest"];
export type TextFilterRequest = Schemas["TextFilterRequest"];
export type FacetsResponse = Schemas["FacetsResponse"];
export type EnumCount = Schemas["EnumCountResponse"];
export type BoolCounts = Schemas["BoolCountsResponse"];
export type NumberRange = Schemas["NumberRangeResponse"];
export type NumberBound = Schemas["NumberBoundResponse"];
export type NewPart = Schemas["DefinePartRequest"];
export type PartRevision = Schemas["UpdatePartRequest"];
export type AttributeProblem = Schemas["AttributeProblemResponse"];
export type AttributeDetails = Schemas["AttributeResponse"];
export type Pinout = Schemas["PinoutResponse"];
export type Pin = Schemas["PinResponse"];
export type PinType = Schemas["PinTypeName"];
export type PinEdit = Schemas["PinRequest"];
export type PinoutReplacement = Schemas["ReplacePinoutRequest"];
export type NewCategory = Schemas["CreateCategoryRequest"];
export type CategoryChange = Schemas["UpdateCategoryRequest"];
export type NewAttribute = Schemas["DefineAttributeRequest"];
export type AttributeChange = Schemas["UpdateAttributeRequest"];
export type AttachmentResponse = Schemas["AttachmentResponse"];
export type AttachmentKind = Schemas["AttachmentKindName"];
export type MediaType = Schemas["MediaTypeName"];
export type ChangeAttachmentRequest = Schemas["ChangeAttachmentRequest"];
export type LocationNode = Schemas["LocationNodeResponse"];
export type LocationResponse = Schemas["LocationResponse"];
export type NewLocation = Schemas["CreateLocationRequest"];
export type LocationChange = Schemas["UpdateLocationRequest"];
export type ReceiveRequest = Schemas["ReceiveRequest"];
export type AdjustRequest = Schemas["AdjustRequest"];
export type MoveRequest = Schemas["MoveRequest"];
export type BalanceResponse = Schemas["BalanceResponse"];
export type MoveResponse = Schemas["MoveResponse"];
export type MovementReason = Schemas["MovementReasonName"];
export type PartTotal = Schemas["PartTotalResponse"];
export type PartStock = Schemas["PartStockResponse"];
export type LotBalance = Schemas["LotBalanceResponse"];
export type UnitResponse = Schemas["UnitResponse"];
export type UnitStatus = Schemas["UnitStatusName"];
export type NewUnitBody = Schemas["NewUnitBody"];
export type ReceiveUnitsRequest = Schemas["ReceiveUnitsRequest"];
export type ReceiveUnitsResponse = Schemas["ReceiveUnitsResponse"];
export type RelabelUnitRequest = Schemas["RelabelUnitRequest"];
export type MoveUnitRequest = Schemas["MoveUnitRequest"];
export type RetireUnitRequest = Schemas["RetireUnitRequest"];
export type RetireReason = Schemas["RetireReasonName"];
export type QuickPartBody = Schemas["QuickPartBody"];
export type QuickStockBody = Schemas["QuickStockBody"];
export type QuickAddRequest = Schemas["QuickAddRequest"];
export type QuickAddResponse = Schemas["QuickAddResponse"];
export type CellProblem = Schemas["CellProblemResponse"];
export type ProblemCode = Schemas["ProblemCodeName"];
export type ImportSheetRequest = Schemas["ImportSheetRequest"];
export type ImportRequest = Schemas["ImportRequest"];
export type ImportPreview = Schemas["ImportPreviewResponse"];
export type ImportRow = Schemas["ImportRowResponse"];
export type PartOutcome = Schemas["PartOutcomeResponse"];
export type PartOutcomeKind = Schemas["PartOutcomeName"];
export type StockOutcome = Schemas["StockOutcomeResponse"];
export type StockOutcomeKind = Schemas["StockOutcomeName"];
export type PlannedUnit = Schemas["PlannedUnitResponse"];
export type ImportSummary = Schemas["ImportSummaryResponse"];
export type ImportedPart = Schemas["ImportedPartResponse"];
export type ImportResult = Schemas["ImportResultResponse"];

export function createApiClient(baseUrl: string) {
  // Look fetch up on every request instead of capturing it now, so anything that
  // wraps it later (test mocks, tracing) is honoured.
  return createClient<paths>({ baseUrl, fetch: (request) => globalThis.fetch(request) });
}

export type ApiClient = ReturnType<typeof createApiClient>;
